apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../task1-hardening/base
images:
- digest: sha256:68c84cca80c9fc90abc0fc8dd647eb6c00acd94c5ed37016838ff9778c7bd598
  name: ledger-api
  newName: ghcr.io/nandhareddy8/ledger-api
