apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../task1-hardening/base
images:
- digest: sha256:78f730843b513e44191f8a703febef695ef7bb2ceac929f8f74a3a0fd4cf2908
  name: ledger-api
  newName: ghcr.io/nandhareddy8/ledger-api
