---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCvyOYQJ/Ltz9Zc/cQOelcvJiYF/mQYr7++Hwbu5zLg3MUCbLzQVR2tcTxyNMSnLOFhCsmXM2C2zd99D1uxD7TVHLikdTSDoVW2dIv6GaA91iGcj9TVD7VY2bpsQhQ6kmFhVPfnGvmselY/aof/r359HGiUPk/uukbkBbrjX0IJ6a71dDOKS+FMoEwdLxN+gvryY7lA4q/WB+5gllU6fFIWWK95vQl7mCkmxHZzFAKXD4m7Fin/V29yTW/MYV+7jmkndrZcO3+eglKKFkAHG64uoKyg1GcPqzEQMsViYZ6zbVpowKbz5NAG7PHn4/jB2OkWH/JIAg0yxToZTQThe6kUkQvKjKY9PcP8apdTAfNZDVDvoKzOJ8yh1qhbMB3Az9GwrJAToDNBDUiR91NQFRhCkSCHGGAcRglis4c0rTt07jmp794gvmq7OGJmx0LIwVU+F1DNjfMCSKHfCB2j5Dfd3+wumntJaPa9FZxsXaG8oTw6/5OkGkL613zNJkMR/el3T/tEMUk7kfq3Sziig+XO5urZ/xN/ToTr/kS8+W/m9dNuhwFN/o04pRs4gbDPTDG8Cfl7PyyRWcw7kO5NAsaWpGIBYAekCV1Hp/EM1C+vgH3dFOFEjVNmuVQEEjRUX0DkgplaWlEHimyphR3T59SaNdkF5/ZtYU+6ZULq339kZfX9ILoijy7uE9wBOJ8cOXoIot/vCLQL79jPErRvFTbFuybwjlEKNVKfvYsm04QO2g==
    STRIPE_API_KEY: AgCGmW4g3oZxsyTSKZraLI6yM1oarFEq14ht9bcd6KiDQgcpu7NPoI4V18uJhjLWZ5C8eA27TpeV6jmlMeF1eG86L4LZd/qucR72kFMgQo+c4v+pnEUN43E9vxIKW0jxQU+qaEnGQvjRelhHgE41NLTBsVKe0MUakMcIqI3Z0vJ8OtlcQEkcs/2t/36Jvc+QKBPZKh0cfDqEWyeT/L/jbDoNGwF2vQpLNMnQCfhUFsLLkvt0fDyAaBCSfCfahVQMhmyy44WjoJVasa1pwD1qgHEqNLrlEzo2x3La7F2xu/p/kQUWAku2l2dTKTD8iUmmcd9GlVLy2gkLLD5biqzgkZFM0FjbL8vRmNttlSv4SyNRjEgy98FlwQs2iaWWuK+++joFccQ5OduYT19M448fJTk8IrrwRsXsM7sfzOBAvReWCC+cci/rNPRi7AlFIaJisJ4XrqQdxF5Q07g7qCrdhrjhSidGFVlL029HjsE6tzD06JYPYudkYcZ7Nm0D8HNXhS58G31KcoDSxczlHTAZpsIC7VnsE3t9np/d1EA94aAvjokoAa2q6uYObSeuEkJ2ZzjdLu/uiQ1Ua+3hwzgItF2bXN8Z+wwjfA2CqtVlCHsPaXumPKJzmj4SFejkDjwM420dbHTn0TvmMPRBaHCWqMCG6XrMuyljteZYPAOBWP6mlDtfOrR+Pygi8K88jNVBlcTjx7v631Ba4m/spkwDIfsQofVtBnb8QAHCSdZuRQicD84GiDOCBHIX
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
